sudo: required
language: bash
services:
- docker
before_install:
- docker build -t jinwuzhao/emacs-python .
deploy:
  provider: script
  script: bash docker_push
  on:
    tags: true
env:
  global:
  - secure: Y/Y6L4n62UAInowp11ZznQ+yi0BpDFUgp2tFltqDN79WYlQbHGiV19ej5ff82GCWwl/XpBjXI1Dd6S1uArFCTF+pQBRJ2AGTrOrn7rtsEdEqos0q63R6/OZFkQLDITZmtMdpbrUO3xm6W40VsX7Uid3yqog7ihyLULWowp2e2lYfegB68aeLBotrsL7b2GRPKgF+4ssoUN0zHFT9V1JILbzf/Q7zCc0s3Etcl1o9Oib03+oqvbQOczry7Qufh/N2GAgy1EgWpkVRLwN1ebsj3hkHo8632NTRPBrxkyQMRFxjA2uLI6F0mDGIMdvQPdH1MaJEon4aDmmT3blYbSQjsDN4PTJQhqgBm7j4X9J2+y8UvmC9u/LrpFg/g+zstZpiR5BXcGmWC6Ozx5XJvFhwUPST4cWEAgum0n1nNuA4FQnh8yFoMmyM4hcmv4Oe4jw21Eegrg2H9kkXnybFk6ex6WEf2O3Jyf7wr32PacTGNAzpRx2HaZHtlMgEGjq3mqo4SpuWHTyXT0GoQpRap1dUI8CAMr99uoiyZUkPjYqxLwiftYF8V/pNZZtydIkQjsHRYCodZSzcP0iOzzk/9iA9UyEWZ9N4dr116oC7iwNe4eNxZrxNQgAG91yzWxEl6cFLUHvKOsFphLCYkwKtvH5Gs50bbaAH7/AVQnPMgqnddQg=
  - secure: O2YQ/1k/cekFyb6RKutNRMjCQG86VHmsuiC1Ihzk3G5V+0zwIc75OtMY5VlEO/sY4r/EsYtpHe18jH87OqLv1MtadS9RUKaUO/1cB3N0l5UQMPp8vaGmYa4rPHhDLQG4y20NatZGiybxZEmKAas6U5oQbtO2SMwuXlsfGwrnadChLRuBnRGEm0fSrkwMJt+nmIbiGX7VqbUc/KP8XS5znIf4DJv1E1Hey41yKu0QWCM7JOt5XZa2spI+z6KjrJ7ufkWEsOHtNkDeGzi5RbcO100ElynEPf7uf0hMbiQehRmwyF5anRjUUFI8svcDKAR24iRTfQogO/MkUpIZX/RnYU4tDlyXd1cFyjdiw2gL4+cFnNMhQbPk2iXLI6r7rvG5m5KpcaAX6lAjnlo5STI1kq4FNCvR/m1x/UjI7HwKKMuh215MbF98gCrzeM8xwRSuylsZQnAnvnkv9YGHJfVRutRwT2irdZZNYWXAf8asZ6MUjBS16Bk9iQmRKrHMdlmsWBUExMqtEHB4OOZgeMKpjl7pMjm5k60zncmaEcpPvc2LBuBs6YzdpoqK6etYHPn3F5mkQL3aZxoIsC/EHzDo9Rmpi8Vz5b+PgyxyQzLDc+pbeSlncANoCypXDkfWbYn4qysGrPAsPLGwAThmJ83n0k36SIUXvkCHZbi+OVY2R+c=
