#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker push jinwuzhao/emacs-python
docker tag jinwuzhao/emacs-python jinwuzhao/emacs-python:$TRAVIS_TAG
docker push jinwuzhao/emacs-python:$TRAVIS_TAG
docker logout
